### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by venkateshbala14031996** [s4chin/Natasha#2]
Traceback (most recent call last):
  File "Natasha.py", line 5, in <module>
    import cleverbot
ImportError: No module named cleverbot

**Comment by s4chin** [comment]
Did you install cleverbot?
Use this command -
`pip install cleverbot`

**Comment by venkateshbala14031996** [comment]
Traceback (most recent call last):
  File "Natasha.py", line 7, in <module>
    import wikipedia
ImportError: No module named wikipedia

**Comment by s4chin** [comment]
Similarly install wikipedia
`pip install wikipedia`
